name : Subhra_Ec2
on:
  push:
      branches:
            - main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print my name
              run: |
                 echo "Subhra"
                 echo "gitbuh-cicd"

            - name: current folder
              run: |
                pwd
            
               
            
      
